// Code generated by bico-admin code generator. DO NOT EDIT.
// Generated at: 2025-07-18 16:06:30

package definitions

import (
	"strings"
)


// CompleteTestModelPermissionRegistrar CompleteTestModel Permission 注册器
type CompleteTestModelPermissionRegistrar struct{}

// GetPermissions 实现 PermissionRegistrar 接口
func (r *CompleteTestModelPermissionRegistrar) GetPermissions() []PermissionDef {
	return completetestmodelPermissionDefs
}

// completetestmodelPermissionDefs CompleteTestModel权限定义
var completetestmodelPermissionDefs = []PermissionDef{
}

// CompleteTestModel权限常量
const (
)

// OrderPermissionRegistrar Order Permission 注册器
type OrderPermissionRegistrar struct{}

// GetPermissions 实现 PermissionRegistrar 接口
func (r *OrderPermissionRegistrar) GetPermissions() []PermissionDef {
	return orderPermissionDefs
}

// orderPermissionDefs Order权限定义
var orderPermissionDefs = []PermissionDef{
}

// Order权限常量
const (
)

// UserPermissionRegistrar User Permission 注册器
type UserPermissionRegistrar struct{}

// GetPermissions 实现 PermissionRegistrar 接口
func (r *UserPermissionRegistrar) GetPermissions() []PermissionDef {
	return userPermissionDefs
}

// userPermissionDefs User权限定义
var userPermissionDefs = []PermissionDef{
}

// User权限常量
const (
)

// ArticlePermissionRegistrar Article Permission 注册器
type ArticlePermissionRegistrar struct{}

// GetPermissions 实现 PermissionRegistrar 接口
func (r *ArticlePermissionRegistrar) GetPermissions() []PermissionDef {
	return articlePermissionDefs
}

// articlePermissionDefs Article权限定义
var articlePermissionDefs = []PermissionDef{
}

// Article权限常量
const (
)

// FieldTypesTestPermissionRegistrar FieldTypesTest Permission 注册器
type FieldTypesTestPermissionRegistrar struct{}

// GetPermissions 实现 PermissionRegistrar 接口
func (r *FieldTypesTestPermissionRegistrar) GetPermissions() []PermissionDef {
	return fieldtypestestPermissionDefs
}

// fieldtypestestPermissionDefs FieldTypesTest权限定义
var fieldtypestestPermissionDefs = []PermissionDef{
	{"system.field_types_test", "FieldTypesTest", "system", "module", 1, "", ""},
	{"system.field_types_test:list", "查看FieldTypesTest列表", "system.field_types_test", "action", 1, "search,filter", "/admin-api/field_types_tests,/admin-api/field_types_tests/:id"},
	{"system.field_types_test:create", "创建FieldTypesTest", "system.field_types_test", "action", 3, "create", "/admin-api/field_types_tests"},
	{"system.field_types_test:update", "编辑FieldTypesTest", "system.field_types_test", "action", 3, "edit,save", "/admin-api/field_types_tests/:id,/admin-api/field_types_tests/:id/status"},
	{"system.field_types_test:delete", "删除FieldTypesTest", "system.field_types_test", "action", 4, "delete", "/admin-api/field_types_tests/:id"},
}

// FieldTypesTest权限常量
const (
	// 查看FieldTypesTest列表权限
	FieldTypesTest_action_1 = "system.field_types_test:list"
	// 创建FieldTypesTest权限
	FieldTypesTest_action_3 = "system.field_types_test:create"
	// 编辑FieldTypesTest权限
	FieldTypesTest_action_3 = "system.field_types_test:update"
	// 删除FieldTypesTest权限
	FieldTypesTest_action_4 = "system.field_types_test:delete"
)


// init 自动注册所有 Permission
func init() {
	// 注册CompleteTestModel Permission
	completetestmodelPermissionRegistrar := &CompleteTestModelPermissionRegistrar{}
	RegisterPermissionRegistrar(completetestmodelPermissionRegistrar)
	// 注册Order Permission
	orderPermissionRegistrar := &OrderPermissionRegistrar{}
	RegisterPermissionRegistrar(orderPermissionRegistrar)
	// 注册User Permission
	userPermissionRegistrar := &UserPermissionRegistrar{}
	RegisterPermissionRegistrar(userPermissionRegistrar)
	// 注册Article Permission
	articlePermissionRegistrar := &ArticlePermissionRegistrar{}
	RegisterPermissionRegistrar(articlePermissionRegistrar)
	// 注册FieldTypesTest Permission
	fieldtypestestPermissionRegistrar := &FieldTypesTestPermissionRegistrar{}
	RegisterPermissionRegistrar(fieldtypestestPermissionRegistrar)
}
