// Code generated by bico-admin code generator. DO NOT EDIT.
// Generated at: 2025-07-18 16:06:30

package initializer

import (
	"gorm.io/gorm"
	"internal/admin/models"
)


// CompleteTestModelMigrationRegistrar CompleteTestModel Migration 注册器
type CompleteTestModelMigrationRegistrar struct{}

// GetMigrations 实现 MigrationRegistrar 接口
func (r *CompleteTestModelMigrationRegistrar) GetMigrations() []interface{} {
	return []interface{}{
		&models.CompleteTestModel{},
	}
}

// MigrateCompleteTestModelTable 迁移CompleteTestModel表
func MigrateCompleteTestModelTable(db *gorm.DB) error {
	return db.AutoMigrate(&models.CompleteTestModel{})
}

// OrderMigrationRegistrar Order Migration 注册器
type OrderMigrationRegistrar struct{}

// GetMigrations 实现 MigrationRegistrar 接口
func (r *OrderMigrationRegistrar) GetMigrations() []interface{} {
	return []interface{}{
		&models.Order{},
	}
}

// MigrateOrderTable 迁移Order表
func MigrateOrderTable(db *gorm.DB) error {
	return db.AutoMigrate(&models.Order{})
}

// UserMigrationRegistrar User Migration 注册器
type UserMigrationRegistrar struct{}

// GetMigrations 实现 MigrationRegistrar 接口
func (r *UserMigrationRegistrar) GetMigrations() []interface{} {
	return []interface{}{
		&models.User{},
	}
}

// MigrateUserTable 迁移User表
func MigrateUserTable(db *gorm.DB) error {
	return db.AutoMigrate(&models.User{})
}

// ArticleMigrationRegistrar Article Migration 注册器
type ArticleMigrationRegistrar struct{}

// GetMigrations 实现 MigrationRegistrar 接口
func (r *ArticleMigrationRegistrar) GetMigrations() []interface{} {
	return []interface{}{
		&models.Article{},
	}
}

// MigrateArticleTable 迁移Article表
func MigrateArticleTable(db *gorm.DB) error {
	return db.AutoMigrate(&models.Article{})
}

// FieldTypesTestMigrationRegistrar FieldTypesTest Migration 注册器
type FieldTypesTestMigrationRegistrar struct{}

// GetMigrations 实现 MigrationRegistrar 接口
func (r *FieldTypesTestMigrationRegistrar) GetMigrations() []interface{} {
	return []interface{}{
		&models.FieldTypesTest{},
	}
}

// MigrateFieldTypesTestTable 迁移FieldTypesTest表
func MigrateFieldTypesTestTable(db *gorm.DB) error {
	return db.AutoMigrate(&models.FieldTypesTest{})
}


// init 自动注册所有 Migration
func init() {
	// 注册CompleteTestModel Migration
	completetestmodelMigrationRegistrar := &CompleteTestModelMigrationRegistrar{}
	RegisterMigrationRegistrar(completetestmodelMigrationRegistrar)
	// 注册Order Migration
	orderMigrationRegistrar := &OrderMigrationRegistrar{}
	RegisterMigrationRegistrar(orderMigrationRegistrar)
	// 注册User Migration
	userMigrationRegistrar := &UserMigrationRegistrar{}
	RegisterMigrationRegistrar(userMigrationRegistrar)
	// 注册Article Migration
	articleMigrationRegistrar := &ArticleMigrationRegistrar{}
	RegisterMigrationRegistrar(articleMigrationRegistrar)
	// 注册FieldTypesTest Migration
	fieldtypestestMigrationRegistrar := &FieldTypesTestMigrationRegistrar{}
	RegisterMigrationRegistrar(fieldtypestestMigrationRegistrar)
}
