# =============================================================================
# Bico Admin 生产环境 Docker Compose 配置
# =============================================================================

version: '3.8'

services:
  # 主应用服务
  bico-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bico-admin-app
    restart: unless-stopped
    ports:
      - "8899:8899"
    environment:
      # 应用配置
      BICO_APP_ENVIRONMENT: production
      BICO_APP_DEBUG: false
      
      # 数据库配置
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: bico_admin
      DB_PASSWORD: ${DB_PASSWORD:-secure_password_123}
      DB_NAME: bico_admin
      
      # Redis 配置
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis_password_123}
      REDIS_DB: 0
      REDIS_CACHE_DB: 1
      
      # JWT 配置 (生产环境必须更改)
      JWT_SECRET: ${JWT_SECRET:-your-very-secure-jwt-secret-key-change-me}
      JWT_EXPIRE: 24h
      
      # 日志配置
      LOG_LEVEL: info
      
      # 缓存配置
      CACHE_DRIVER: redis
      
      # 上传配置
      UPLOAD_MAX_SIZE: 50MB
      UPLOAD_MAX_FILES: 20
      UPLOAD_BASE_URL: ${UPLOAD_BASE_URL:-}
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
      - ./config/app.prod.yml:/app/config/app.yml:ro
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - bico-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8899/admin-api/auth/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: bico-admin-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password_123}
      MYSQL_DATABASE: bico_admin
      MYSQL_USER: bico_admin
      MYSQL_PASSWORD: ${DB_PASSWORD:-secure_password_123}
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./deployments/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    networks:
      - bico-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: bico-admin-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis_password_123}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - bico-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  # Nginx 反向代理 (可选)
  nginx:
    image: nginx:alpine
    container_name: bico-admin-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployments/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deployments/nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - bico-admin
    networks:
      - bico-network

# 网络配置
networks:
  bico-network:
    driver: bridge

# 数据卷配置
volumes:
  app_data:
    driver: local
  app_logs:
    driver: local
  mysql_data:
    driver: local
  redis_data:
    driver: local
  nginx_logs:
    driver: local
