# Bico Admin 应用配置文件

app:
  name: "bico-admin"
  version: "1.0.0"
  environment: "development"
  debug: true

server:
  host: "0.0.0.0"
  port: 8899
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

database:
  driver: "sqlite"
  database: "data/bico_admin.db"
  max_idle_conns: 5
  max_open_conns: 10
  conn_max_lifetime: "1h"

  # MySQL 配置示例
  # driver: "mysql"
  # host: "localhost"
  # port: 3306
  # username: "root"
  # password: "password"
  # database: "bico_admin"
  # charset: "utf8mb4"
  # max_idle_conns: 10
  # max_open_conns: 100
  # conn_max_lifetime: "1h"

  # PostgreSQL 配置示例
  # driver: "postgres"
  # host: "localhost"
  # port: 5432
  # username: "postgres"
  # password: "password"
  # database: "bico_admin"
  # max_idle_conns: 10
  # max_open_conns: 100
  # conn_max_lifetime: "1h"

redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"

log:
  level: "info"
  format: "json"
  output: "stdout"
  filename: "logs/app.log"
  max_size: 100
  max_age: 7
  max_backups: 10
  compress: true

jwt:
  secret: "your-secret-key-change-in-production"
  issuer: "bico-admin"
  expire_time: "24h"
