basePath: /api
host: localhost:8080
info:
  contact:
    name: API Support
    url: https://github.com/slowlyo/bico-admin
  description: 对外 API 模块文档
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: https://github.com/slowlyo/bico-admin
  title: Bico Admin Open API
  version: "1.0"
paths: {}
swagger: "2.0"
